use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

use crate::config::settings::{BridgeSettings, Settings};
use crate::core::routing::BridgeType;

pub fn tor_data_dir() -> Result<PathBuf> {
    let proj_dirs = directories::ProjectDirs::from("org", "Onionymous", "Onionymous")
        .context("Could not determine data directory")?;
    let dir = proj_dirs.data_local_dir().join("tor-data");
    fs::create_dir_all(&dir).with_context(|| format!("Creating {}", dir.display()))?;
    Ok(dir)
}

pub fn torrc_path() -> Result<PathBuf> {
    Ok(tor_data_dir()?.join("torrc"))
}

pub fn write_torrc(settings: &Settings) -> Result<PathBuf> {
    let path = torrc_path()?;
    let contents = generate_torrc_contents(settings)?;
    fs::write(&path, contents).with_context(|| format!("Writing torrc to {}", path.display()))?;
    log::debug!("Wrote torrc at {}", path.display());
    Ok(path)
}

pub fn generate_torrc_contents(settings: &Settings) -> Result<String> {
    let data_dir = tor_data_dir()?;
    let mut lines: Vec<String> = Vec::new();

    lines.push("# torrc generated by Onionymous — do not edit manually".into());
    lines.push(format!("# Generated at: {}", chrono::Local::now().to_rfc3339()));
    lines.push(String::new());

    lines.push(format!("SOCKSPort 127.0.0.1:{}", settings.socks_port));
    lines.push(format!("ControlPort 127.0.0.1:{}", settings.control_port));
    lines.push(format!("DNSPort 127.0.0.1:{}", settings.dns_port));
    lines.push(String::new());

    lines.push("CookieAuthentication 1".into());
    lines.push(format!(
        "DataDirectory \"{}\"",
        data_dir.display().to_string().replace('\\', "/")
    ));
    lines.push(String::new());

    let geoip_paths = find_geoip_files();
    let has_geoip = geoip_paths.is_some();
    if let Some((geoip, geoip6)) = &geoip_paths {
        lines.push(format!(
            "GeoIPFile \"{}\"",
            geoip.display().to_string().replace('\\', "/")
        ));
        lines.push(format!(
            "GeoIPv6File \"{}\"",
            geoip6.display().to_string().replace('\\', "/")
        ));
    }
    lines.push(String::new());

    if let Some(code) = &settings.exit_country {
        lines.push(format!("ExitNodes {{{}}}", code.to_lowercase()));
        if has_geoip {
            lines.push("StrictNodes 1".into());
        } else {
            lines.push("# StrictNodes disabled: geoip files not found".into());
            log::warn!(
                "GeoIP files not found — country filter will be best-effort. \
                 Place geoip and geoip6 next to tor.exe for strict enforcement."
            );
        }
    }

    if let Some(code) = &settings.entry_country {
        lines.push(format!("EntryNodes {{{}}}", code.to_lowercase()));
    }

    if !settings.excluded_countries.is_empty() && has_geoip {
        let joined = settings
            .excluded_countries
            .iter()
            .map(|c| format!("{{{}}}", c.to_lowercase()))
            .collect::<Vec<_>>()
            .join(",");
        lines.push(format!("ExcludeNodes {joined}"));
        lines.push(format!("ExcludeExitNodes {joined}"));
    } else if !settings.excluded_countries.is_empty() {
        log::warn!("Excluded countries ignored: geoip files not found");
    }

    lines.push(String::new());

    if settings.bridge.enabled {
        lines.push("UseBridges 1".into());
        append_bridge_config(&mut lines, &settings.bridge)?;
    }

    lines.push(String::new());
    lines.push("ClientOnly 1".into());
    lines.push("AvoidDiskWrites 1".into());
    lines.push("CircuitBuildTimeout 60".into());
    lines.push(String::new());

    Ok(lines.join("\n"))
}

fn find_geoip_files() -> Option<(PathBuf, PathBuf)> {
    if let (Some(g4), Some(g6)) = (
        crate::resources::geoip_path(),
        crate::resources::geoip6_path(),
    ) {
        log::info!("Using extracted geoip files from runtime dir");
        return Some((g4, g6));
    }

    let exe = std::env::current_exe().ok()?;
    let exe_dir = exe.parent()?;
    let candidates = [
        exe_dir.join("resources").join("tor"),
        exe_dir.join("resources").join("tor").join("data"),
        exe_dir.join("resources").join("geoip"),
        exe_dir.to_path_buf(),
    ];
    for dir in candidates.iter() {
        let g4 = dir.join("geoip");
        let g6 = dir.join("geoip6");
        if g4.is_file() && g6.is_file() {
            log::info!("Using geoip files from {}", dir.display());
            return Some((g4, g6));
        }
    }
    None
}

fn append_bridge_config(lines: &mut Vec<String>, bridge: &BridgeSettings) -> Result<()> {
    let pt_dir = match crate::resources::runtime_dir() {
        Ok(d) => d.join("pluggable_transports"),
        Err(e) => {
            log::warn!("Could not resolve runtime dir for PT binaries: {e}");
            return Ok(());
        }
    };
    let pt_path = |name: &str| -> String {
        pt_dir
            .join(name)
            .display()
            .to_string()
            .replace('\\', "/")
    };

    match bridge.bridge_type {
        BridgeType::Obfs4 => {
            lines.push(format!(
                "ClientTransportPlugin obfs4,meek_lite exec \"{}\"",
                pt_path("lyrebird.exe")
            ));
            let custom: Vec<&str> = bridge
                .custom_bridges
                .iter()
                .map(|s| s.trim())
                .filter(|s| !s.is_empty())
                .collect();
            if !custom.is_empty() {
                for line in custom {
                    append_bridge_line(lines, line);
                }
            } else {
                for line in crate::tor::bridges::default_obfs4_bridges() {
                    lines.push(format!("Bridge {}", line));
                }
            }
        }
        BridgeType::Snowflake => {
            lines.push(format!(
                "ClientTransportPlugin snowflake exec \"{}\"",
                pt_path("snowflake-client.exe")
            ));
            lines.push(format!(
                "Bridge {}",
                crate::tor::bridges::default_snowflake_bridge()
            ));
        }

        BridgeType::Conjure => {
            lines.push(format!(
                "ClientTransportPlugin conjure exec \"{}\"",
                pt_path("conjure-client.exe")
            ));
            lines.push(format!(
                "Bridge {}",
                crate::tor::bridges::default_conjure_bridge()
            ));
        }

        BridgeType::Custom => {
            let mut needs_obfs4 = false;
            let mut needs_snowflake = false;
            let mut needs_conjure = false;
            for raw in &bridge.custom_bridges {
                let l = raw.trim().to_lowercase();
                if l.contains("obfs4") || l.contains("meek_lite") {
                    needs_obfs4 = true;
                }
                if l.contains("snowflake") {
                    needs_snowflake = true;
                }
                if l.contains("conjure") {
                    needs_conjure = true;
                }
            }
            if needs_obfs4 {
                lines.push(format!(
                    "ClientTransportPlugin obfs4,meek_lite exec \"{}\"",
                    pt_path("lyrebird.exe")
                ));
            }
            if needs_snowflake {
                lines.push(format!(
                    "ClientTransportPlugin snowflake exec \"{}\"",
                    pt_path("snowflake-client.exe")
                ));
            }
            if needs_conjure {
                lines.push(format!(
                    "ClientTransportPlugin conjure exec \"{}\"",
                    pt_path("conjure-client.exe")
                ));
            }
            for raw in &bridge.custom_bridges {
                let trimmed = raw.trim();
                if trimmed.is_empty() {
                    continue;
                }
                append_bridge_line(lines, trimmed);
            }
        }
    }
    Ok(())
}

fn append_bridge_line(lines: &mut Vec<String>, raw: &str) {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return;
    }
    if trimmed.to_lowercase().starts_with("bridge ") {
        lines.push(trimmed.to_string());
    } else {
        lines.push(format!("Bridge {}", trimmed));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn torrc_includes_configured_ports() {
        let settings = Settings::default();
        let txt = generate_torrc_contents(&settings).unwrap();
        assert!(txt.contains("SOCKSPort 127.0.0.1:9050"));
        assert!(txt.contains("ControlPort 127.0.0.1:9051"));
    }

    #[test]
    fn torrc_includes_exit_country_when_set() {
        let mut settings = Settings::default();
        settings.exit_country = Some("DE".into());
        let txt = generate_torrc_contents(&settings).unwrap();
        assert!(txt.contains("ExitNodes {de}"));
        assert!(txt.contains("StrictNodes 1"));
    }
}
